# Generated by Django 6.0.2 on 2026-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_no", models.CharField(max_length=10, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                ("has_ac", models.BooleanField(default=False)),
                ("has_attached_washroom", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
